import type { SiteContent } from './types';

export const ar: SiteContent = {
  locale: 'ar',
  dir: 'rtl',
  path: '/ar',
  htmlLangAlt: 'en',
  altPath: '/',
  meta: {
    title: 'محمد أيمن مصبح — مطوّر Full Stack أول',
    description:
      'أبني الأنظمة الخلفية التي تقف خلف منتجات يستخدمها الملايين — ست سنوات في هندسة Laravel و PHP عبر منتجات التعليم الإلكتروني والأسواق الرقمية وبرمجيات الأعمال.',
  },
  identity: {
    name: 'محمد أيمن مصبح',
    title: 'مطوّر Full Stack أول',
    subtitle: 'هندسة الأنظمة الخلفية · Laravel و PHP',
    location: 'دير البلح، فلسطين',
    availability: 'متاح للعمل عن بُعد (دول الخليج ودولياً)',
  },
  contact: {
    email: 'mhmd.musabeh@gmail.com',
    phone: '+970 597 669 248',
    github: 'https://github.com/phpMuhammed',
  },
  nav: {
    work: 'الأعمال',
    skills: 'المهارات',
    about: 'نبذة عني',
    contact: 'تواصل',
    languageToggleLabel: 'English',
    themeToggleLightLabel: 'التبديل إلى الوضع الفاتح',
    themeToggleDarkLabel: 'التبديل إلى الوضع الداكن',
    skipToContent: 'تخطي إلى المحتوى',
    menuLabel: 'القائمة',
  },
  hero: {
    positioning:
      'أبني الأنظمة الخلفية التي تقف خلف منتجات يستخدمها الملايين — ست سنوات في هندسة Laravel و PHP عبر منتجات التعليم الإلكتروني والأسواق الرقمية وبرمجيات الأعمال.',
    downloadCvLabel: 'تحميل السيرة الذاتية',
    getInTouchLabel: 'تواصل معي',
    githubLabel: 'GitHub',
    emailLabel: 'البريد الإلكتروني',
    phoneLabel: 'الهاتف',
  },
  work: {
    heading: 'الأعمال المختارة',
    websiteLabel: 'الموقع الإلكتروني',
    linkedinLabel: 'LinkedIn',
    entries: [
      {
        slug: 'istoria',
        flagship: true,
        name: 'iStoria — منصّة تعلّم الإنجليزية',
        role: 'مطوّر Backend',
        dates: '2020 – 2024',
        metricBadge: '+5,000,000 متعلّم',
        website: 'https://www.istoria.sa/',
        linkedin: 'https://www.linkedin.com/company/istoria-app',
        description:
          'منصّة تعليمية موجّهة للسوق السعودي والناطقين بالعربية. أربع سنوات من الملكية التقنية المتواصلة للـ Backend حتى أصبح المنتج من أكبر تطبيقات تعلّم الإنجليزية في المنطقة.',
        highlights: [
          'تصميم وصيانة الـ Backend بلغة Laravel/PHP وطبقة الـ RESTful API التي تُشغّل تطبيقات الهاتف والويب',
          'تصميم نموذج البيانات العلائقي على MySQL/PostgreSQL وتطويره بأمان عبر أربع سنوات من خلال migrations منضبطة وفهرسة وتحسين للاستعلامات',
          'الحفاظ على استقرار زمن الاستجابة مع نمو حجم الاستخدام عبر استراتيجيات التخزين المؤقت بـ Redis والمعالجة الخلفية عبر الطوابير وتحسين الأداء الموجّه',
          'تنفيذ المصادقة والصلاحيات وتحديد معدّل الطلبات لحماية واجهة برمجية عامة عالية الحِمل',
          'دعم المحتوى ثنائي اللغة (عربي/إنجليزي) وتسليم الدروس الغنيّة بالوسائط مع دعم كامل لاتجاه RTL',
          'الموازنة بين التسليم المستمر للمزايا واستقرار بيئة الإنتاج لملايين المستخدمين النشطين',
        ],
        techTags: [
          'Laravel',
          'PHP',
          'MySQL',
          'PostgreSQL',
          'Redis',
          'REST API',
          'Queues',
          'Caching',
          'Performance Optimization',
          'PHPUnit',
        ],
        accentColor: '#0d9488',
        websiteLinkLabel: 'زيارة موقع iStoria — يفتح في نافذة جديدة',
        linkedinLinkLabel: 'عرض iStoria على LinkedIn — يفتح في نافذة جديدة',
      },
      {
        slug: 'onestudio',
        name: 'One Studio',
        role: 'مهندس برمجيات Full Stack',
        dates: 'June 2024 – July 2026',
        linkedin: 'https://www.linkedin.com/company/onestudio-co',
        description:
          'فريق هندسي متعدّد المشاريع. تسليم عدّة منتجات موجّهة للعملاء بدءاً من تحليل المتطلبات وتصميم النظام وحتى الإطلاق.',
        highlights: [
          'تسليم عدّة منتجات موجّهة للعملاء، ونقل المزايا من المتطلبات وتصميم النظام إلى التنفيذ والمراجعة والإطلاق',
          'تأسيس منهجية تطوير مدعومة بالذكاء الاصطناعي (Cursor AI و Claude AI و GitHub Copilot) مقترنة بممارسات هندسية منضبطة',
          'القيام بدور تقني قيادي في مراجعة الكود والتوثيق التقني وإرشاد الفريق عبر قواعد كود Laravel المشتركة',
          'العمل ضمن منهجية Agile/Scrum باستخدام Jira وتحويل تصاميم Figma إلى واجهات وواجهات برمجية في الإنتاج',
        ],
        techTags: ['Laravel', 'PHP', 'Agile/Scrum', 'Jira', 'Figma', 'Cursor AI', 'GitHub Copilot'],
        accentColor: '#1d4ed8',
        linkedinLinkLabel: 'عرض One Studio على LinkedIn — يفتح في نافذة جديدة',
      },
      {
        slug: 'darent',
        name: 'Darent — منصّة حجز العقارات',
        role: 'مطوّر Backend (ضمن فريق One Studio)',
        dates: '~8 months',
        metricBadge: 'السوق السعودي',
        website: 'https://darent.com/en',
        linkedin: 'https://www.linkedin.com/company/darent',
        description:
          'منصّة سعودية لعرض العقارات والحجوزات والإقامات قصيرة الأمد — مجال يتّسم بتعقيد عالٍ في إدارة التوفّر والتسعير والمعاملات.',
        highlights: [
          'بناء وظائف الـ Backend الخاصة بعرض العقارات والحجوزات والإقامات قصيرة الأمد',
          'دمج بوابة HyperPay للمدفوعات الإلكترونية الإقليمية و Twilio Verify للمصادقة عبر رمز التحقق',
          'دمج Firebase و MoEngage للإشعارات وتفاعل المستخدمين',
          'تقديم تجربة ثنائية اللغة بالكامل عبر Spatie Translatable وإدارة وسائط غنية عبر Spatie Media Library مع دعم محتوى RTL',
          'تنفيذ البحث عبر Laravel Scout والمعالجة الخلفية عبر Laravel Queues و Scheduler والمراقبة عبر Laravel Telescope',
        ],
        techTags: ['Laravel', 'HyperPay', 'Twilio Verify', 'Firebase', 'MoEngage', 'Laravel Scout', 'Spatie', 'MySQL'],
        accentColor: '#b45309',
        websiteLinkLabel: 'زيارة موقع Darent — يفتح في نافذة جديدة',
        linkedinLinkLabel: 'عرض Darent على LinkedIn — يفتح في نافذة جديدة',
      },
      {
        slug: 'captab',
        name: 'CapTab — منصّة إدارة الصيدليات',
        role: 'مطوّر Backend',
        subLabel: 'منتج SaaS للأعمال، طُوّر بالتوازي مع العمل بدوام كامل',
        dates: '2023 – Present',
        metricBadge: '+70 صيدلية',
        website: 'https://new.captabapp.com',
        description:
          'منصّة لإدارة الصيدليات تعمل بمبدأ Offline-First، تستخدمها صيدليات مستقلّة في فلسطين والمنطقة.',
        highlights: [
          'تصميم وبناء المنصّة بالكامل، من نمذجة البيانات وهندسة الـ Backend وحتى الواجهات البرمجية ولوحات الإدارة',
          'هندسة معمارية Offline-First ونموذج مزامنة للبيانات يتيح للصيدليات مواصلة العمل رغم انقطاع الإنترنت والكهرباء، ثم مطابقة البيانات بسلاسة عند عودة الاتصال',
          'تطبيق Domain-Driven Design ومبادئ SOLID وأنماط التصميم للحفاظ على قابلية صيانة مجال عمل حسّاس مع نمو قاعدة العملاء',
          'بناء واجهات RESTful API مع مصادقة Sanctum وصلاحيات قائمة على الأدوار عبر Filament Shield ولوحات إدارة بـ FilamentPHP',
          'حماية المنطق الحسّاس للمخزون والإيرادات عبر TDD باستخدام Pest PHP و PHPUnit',
        ],
        techTags: ['Laravel', 'Offline-First', 'DDD', 'FilamentPHP', 'Sanctum', 'Pest PHP', 'Redis', 'PostgreSQL'],
        accentColor: '#4338ca',
        websiteLinkLabel: 'زيارة موقع CapTab — يفتح في نافذة جديدة',
      },
    ],
  },
  skills: {
    heading: 'المهارات',
    groups: [
      {
        label: 'الهندسة والتصميم',
        items: [
          'System Design',
          'Scalable Architecture',
          'Backend Architecture',
          'Domain-Driven Design (DDD)',
          'Event-Driven Architecture',
          'API Design',
          'MVC',
          'SOLID Principles',
          'Design Patterns',
          'Authentication & Authorization',
          'Rate Limiting',
        ],
      },
      {
        label: 'الأنظمة الخلفية',
        items: [
          'PHP',
          'Laravel',
          'RESTful APIs',
          'OOP',
          'Eloquent ORM',
          'Laravel Sanctum',
          'Queues',
          'Scheduler',
          'Scout',
          'Telescope',
          'FilamentPHP',
          'Filament Shield',
          'Spatie Media Library',
          'Spatie Translatable',
        ],
      },
      {
        label: 'قواعد البيانات والأداء',
        items: [
          'MySQL',
          'PostgreSQL',
          'Database Design',
          'Data Modeling',
          'Query Optimization',
          'Indexing',
          'Migrations & Seeders',
          'Redis',
          'Caching Strategies',
          'Queue Management',
          'Performance Optimization',
          'Scalability',
        ],
      },
      {
        label: 'الاختبار والجودة',
        items: ['Test-Driven Development (TDD)', 'Pest PHP', 'PHPUnit', 'Unit / Feature / Integration Testing', 'Code Review'],
      },
      {
        label: 'الواجهات والأدوات',
        items: [
          'JavaScript',
          'HTML5',
          'CSS3',
          'Bootstrap',
          'Vite',
          'Git',
          'GitHub',
          'Nginx',
          'Composer',
          'Postman',
          'Jira',
          'VS Code',
          'Figma design handoff',
          'Cursor AI',
          'Claude AI',
          'GitHub Copilot',
        ],
      },
      {
        label: 'التكاملات وأسلوب العمل',
        items: [
          'HyperPay',
          'Twilio Verify',
          'Firebase',
          'MoEngage',
          'Payment Gateway Integration',
          'Agile/Scrum',
          'Mentoring',
          'Technical Documentation',
          'Problem Solving',
          'Stakeholder Communication',
        ],
      },
    ],
  },
  about: {
    heading: 'نبذة عني',
    summary:
      'مهندس برمجيات بخبرة تتجاوز ست سنوات في تصميم وبناء وتوسيع منصّات ويب في بيئات الإنتاج، متخصّص في هندسة الأنظمة الخلفية بـ Laravel و PHP مع ملكية كاملة لدورة التسليم. خبرة قوية في تصميم الأنظمة وتصميم واجهات RESTful API و Domain-Driven Design و Test-Driven Development، وعمق عملي في MySQL و PostgreSQL والتخزين المؤقت بـ Redis وإدارة الطوابير وتحسين الاستعلامات. خبرة في التكامل مع مزوّدي الدفع والتفاعل الإقليميين وتسليم منتجات ثنائية اللغة في دول الخليج.',
    educationHeading: 'التعليم',
    education: 'بكالوريوس هندسة برمجيات — الجامعة الإسلامية بغزة، 2019',
    languagesHeading: 'اللغات',
    languages: 'العربية — اللغة الأم · الإنجليزية — إتقان مهني',
  },
  contactSection: {
    heading: 'تواصل',
    cvNote: 'السيرة الذاتية متاحة بالإنجليزية',
    downloadCvLabel: 'تحميل السيرة الذاتية (PDF)',
    emailLabel: 'البريد الإلكتروني',
    phoneLabel: 'الهاتف',
    githubLabel: 'GitHub',
    locationLabel: 'الموقع',
  },
  footer: {
    builtWith: 'بُني باستخدام Astro',
  },
};
