import type { SiteContent } from './types';

export const en: SiteContent = {
  locale: 'en',
  dir: 'ltr',
  path: '/',
  htmlLangAlt: 'ar',
  altPath: '/ar',
  meta: {
    title: 'Mohammed Ayman Musabeh — Senior Full Stack Developer',
    description:
      'I design and build the backends behind products that reach millions — six years of Laravel and PHP architecture across ed-tech, marketplaces and B2B SaaS.',
  },
  identity: {
    name: 'Mohammed Ayman Musabeh',
    title: 'Senior Full Stack Developer',
    subtitle: 'Backend Architecture · Laravel & PHP',
    location: 'Deir al-Balah, Palestine',
    availability: 'Open to remote roles (GCC & international)',
  },
  contact: {
    email: 'mhmd.musabeh@gmail.com',
    phone: '+970 597 669 248',
    github: 'https://github.com/phpMuhammed',
  },
  nav: {
    work: 'Work',
    skills: 'Skills',
    about: 'About',
    contact: 'Contact',
    languageToggleLabel: 'العربية',
    themeToggleLightLabel: 'Switch to light theme',
    themeToggleDarkLabel: 'Switch to dark theme',
    skipToContent: 'Skip to content',
    menuLabel: 'Menu',
  },
  hero: {
    positioning:
      'I design and build the backends behind products that reach millions — six years of Laravel and PHP architecture across ed-tech, marketplaces and B2B SaaS.',
    downloadCvLabel: 'Download CV',
    getInTouchLabel: 'Get in touch',
    githubLabel: 'GitHub',
    emailLabel: 'Email',
    phoneLabel: 'Phone',
  },
  work: {
    heading: 'Selected Work',
    websiteLabel: 'Website',
    linkedinLabel: 'LinkedIn',
    entries: [
      {
        slug: 'istoria',
        flagship: true,
        name: 'iStoria — English-Learning Platform',
        role: 'Backend Developer',
        dates: '2020 – 2024',
        metricBadge: '5,000,000+ learners',
        website: 'https://www.istoria.sa/',
        linkedin: 'https://www.linkedin.com/company/istoria-app',
        description:
          'Consumer ed-tech platform serving the Saudi and Arabic-speaking market. Four years of continuous backend ownership as the product grew into one of the largest English-learning apps in the region.',
        highlights: [
          'Architected and maintained the Laravel/PHP backend and RESTful API layer powering the mobile and web clients',
          'Designed the relational data model in MySQL/PostgreSQL and evolved it safely across four years through disciplined migrations, indexing and query optimization',
          'Kept response times stable as traffic scaled using Redis caching strategies, queue-driven background processing and targeted performance optimization',
          'Implemented authentication, authorization and rate limiting to secure a high-volume public API',
          'Delivered bilingual Arabic/English content handling and media-heavy lesson delivery with full RTL support',
          'Balanced continuous feature delivery against production stability for millions of active users',
        ],
        techTags: [
          'Laravel',
          'PHP',
          'MySQL',
          'PostgreSQL',
          'Redis',
          'REST API',
          'Queues',
          'Caching',
          'Performance Optimization',
          'PHPUnit',
        ],
        accentColor: '#0d9488',
        websiteLinkLabel: 'Visit iStoria website — opens in new tab',
        linkedinLinkLabel: 'View iStoria on LinkedIn — opens in new tab',
      },
      {
        slug: 'onestudio',
        name: 'One Studio',
        role: 'Full Stack Software Engineer (Vibe Coder Engineer)',
        dates: 'June 2024 – July 2026',
        linkedin: 'https://www.linkedin.com/company/onestudio-co',
        description:
          'Multi-project product engineering team. Delivered several client-facing products from requirements and system design through to release.',
        highlights: [
          'Delivered multiple client-facing products, taking features from requirements and system design through implementation, review and release',
          'Pioneered an AI-assisted development workflow (Cursor AI, Claude AI, GitHub Copilot) paired with disciplined engineering practice',
          'Acted as a senior technical voice in code review, technical documentation and mentoring across shared Laravel codebases',
          'Worked in Agile/Scrum using Jira, converting Figma design handoffs into production frontend and API work',
        ],
        techTags: ['Laravel', 'PHP', 'Agile/Scrum', 'Jira', 'Figma', 'Cursor AI', 'GitHub Copilot'],
        accentColor: '#1d4ed8',
        linkedinLinkLabel: 'View One Studio on LinkedIn — opens in new tab',
      },
      {
        slug: 'darent',
        name: 'Darent — Property Booking Marketplace',
        role: 'Backend Developer (as part of the One Studio team)',
        dates: '~8 months',
        metricBadge: 'Saudi market',
        website: 'https://darent.com/en',
        linkedin: 'https://www.linkedin.com/company/darent',
        description:
          'Saudi marketplace platform for property listings, bookings and short-term stays — a domain with heavy availability, pricing and transactional complexity.',
        highlights: [
          'Built backend functionality covering property listings, bookings and short-term stays',
          'Integrated HyperPay for regional online payments and Twilio Verify for OTP authentication',
          'Integrated Firebase and MoEngage for notifications and user engagement',
          'Delivered a fully bilingual Arabic/English experience with Spatie Translatable and rich media handling via Spatie Media Library, including RTL content',
          'Implemented search with Laravel Scout, background processing with Laravel Queues and Scheduler, and observability with Laravel Telescope',
        ],
        techTags: ['Laravel', 'HyperPay', 'Twilio Verify', 'Firebase', 'MoEngage', 'Laravel Scout', 'Spatie', 'MySQL'],
        accentColor: '#b45309',
        websiteLinkLabel: 'Visit Darent website — opens in new tab',
        linkedinLinkLabel: 'View Darent on LinkedIn — opens in new tab',
      },
      {
        slug: 'captab',
        name: 'CapTab — Pharmacy Management Platform',
        role: 'Backend Developer',
        subLabel: 'B2B SaaS, built alongside full-time engagements',
        dates: '2023 – Present',
        metricBadge: '70+ pharmacies',
        website: 'https://new.captabapp.com',
        description:
          'Offline-first pharmacy management platform used by independent pharmacies across Palestine and the region.',
        highlights: [
          'Designed and built the platform end to end, from data modeling and backend architecture through to API and admin interfaces',
          'Engineered the offline-first architecture and data synchronization model that lets pharmacies keep trading through unstable connectivity and power outages, then reconcile cleanly once back online',
          'Applied Domain-Driven Design, SOLID principles and design patterns to keep a business-critical domain maintainable as the customer base grew',
          'Built RESTful APIs with Sanctum authentication and role-based authorization via Filament Shield, with back-office panels in FilamentPHP',
          'Protected stock- and revenue-critical logic with TDD using Pest PHP and PHPUnit',
        ],
        techTags: ['Laravel', 'Offline-First', 'DDD', 'FilamentPHP', 'Sanctum', 'Pest PHP', 'Redis', 'PostgreSQL'],
        accentColor: '#4338ca',
        websiteLinkLabel: 'Visit CapTab website — opens in new tab',
      },
    ],
  },
  skills: {
    heading: 'Skills',
    groups: [
      {
        label: 'Architecture & Design',
        items: [
          'System Design',
          'Scalable Architecture',
          'Backend Architecture',
          'Domain-Driven Design (DDD)',
          'Event-Driven Architecture',
          'API Design',
          'MVC',
          'SOLID Principles',
          'Design Patterns',
          'Authentication & Authorization',
          'Rate Limiting',
        ],
      },
      {
        label: 'Backend',
        items: [
          'PHP',
          'Laravel',
          'RESTful APIs',
          'OOP',
          'Eloquent ORM',
          'Laravel Sanctum',
          'Queues',
          'Scheduler',
          'Scout',
          'Telescope',
          'FilamentPHP',
          'Filament Shield',
          'Spatie Media Library',
          'Spatie Translatable',
        ],
      },
      {
        label: 'Databases & Performance',
        items: [
          'MySQL',
          'PostgreSQL',
          'Database Design',
          'Data Modeling',
          'Query Optimization',
          'Indexing',
          'Migrations & Seeders',
          'Redis',
          'Caching Strategies',
          'Queue Management',
          'Performance Optimization',
          'Scalability',
        ],
      },
      {
        label: 'Testing & Quality',
        items: ['Test-Driven Development (TDD)', 'Pest PHP', 'PHPUnit', 'Unit / Feature / Integration Testing', 'Code Review'],
      },
      {
        label: 'Frontend, DevOps & Tools',
        items: [
          'JavaScript',
          'HTML5',
          'CSS3',
          'Bootstrap',
          'Vite',
          'Git',
          'GitHub',
          'Nginx',
          'Composer',
          'Postman',
          'Jira',
          'VS Code',
          'Figma design handoff',
          'Cursor AI',
          'Claude AI',
          'GitHub Copilot',
        ],
      },
      {
        label: 'Integrations & Ways of Working',
        items: [
          'HyperPay',
          'Twilio Verify',
          'Firebase',
          'MoEngage',
          'Payment Gateway Integration',
          'Agile/Scrum',
          'Mentoring',
          'Technical Documentation',
          'Problem Solving',
          'Stakeholder Communication',
        ],
      },
    ],
  },
  about: {
    heading: 'About',
    summary:
      'Software Engineer with 6+ years of experience designing, building and scaling production web platforms, specializing in Laravel and PHP backend architecture with full stack delivery ownership. Strong in system design, RESTful API design, Domain-Driven Design and Test-Driven Development, with hands-on depth in MySQL, PostgreSQL, Redis caching, queue management and query optimization. Experienced with regional payment and engagement providers and bilingual Arabic/English product delivery across the GCC.',
    educationHeading: 'Education',
    education: 'Bachelor of Science in Software Engineering — Islamic University of Gaza, 2019',
    languagesHeading: 'Languages',
    languages: 'Arabic — Native · English — Professional working proficiency',
  },
  contactSection: {
    heading: 'Contact',
    downloadCvLabel: 'Download CV (PDF)',
    emailLabel: 'Email',
    phoneLabel: 'Phone',
    githubLabel: 'GitHub',
    locationLabel: 'Location',
  },
  footer: {
    builtWith: 'Built with Astro',
  },
};
